<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <AssemblyName>PerformanceMonitor.Shared</AssemblyName>
        <RootNamespace>TaskManager</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <AvaloniaResource Include="Assets\**" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="12.1.3" />
        <PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.3" />
        <PackageReference Include="Avalonia.Fonts.Inter" Version="12.1.3" />
        <PackageReference Include="AvaloniaUI.DiagnosticsSupport" Version="2.2.0" />
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.2.2" />
        <PackageReference Include="Hardware.Info" Version="100.0.1.1" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="System.Management" Version="8.0.0" />
        <PackageReference Include="System.Diagnostics.PerformanceCounter" Version="8.0.0" />
    </ItemGroup>
</Project>