<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
        <AssemblyName>PerformanceMonitor</AssemblyName>
        <RootNamespace>TaskManager</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia.Desktop" Version="12.1.3" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\PerformanceMonitor.Shared\PerformanceMonitor.Shared.csproj" />
    </ItemGroup>
</Project>